// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microtx/v1/msgs.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgMicrotx A Msg used to send funds from one Althea network wallet to another,
// via an automated device. Facilitates Liquid Infrastructure by automatically
// redirecting funds received by Tokenized Accounts beyond configured amounts to the EVM.
// SENDER The account sending funds to receiver, must also be the signer of the
// message
// RECEIVER The account receiving funds from sender
// AMOUNTS The tokens and their quantities which should be transferred, these
// must be Cosmos coins registered as ERC20s, or the Cosmos representation of ERC20s
type MsgMicrotx struct {
	Sender   string       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string       `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amounts  []types.Coin `protobuf:"bytes,3,rep,name=amounts,proto3" json:"amounts"`
}

func (m *MsgMicrotx) Reset()         { *m = MsgMicrotx{} }
func (m *MsgMicrotx) String() string { return proto.CompactTextString(m) }
func (*MsgMicrotx) ProtoMessage()    {}
func (*MsgMicrotx) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{0}
}
func (m *MsgMicrotx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMicrotx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMicrotx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMicrotx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMicrotx.Merge(m, src)
}
func (m *MsgMicrotx) XXX_Size() int {
	return m.Size()
}
func (m *MsgMicrotx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMicrotx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMicrotx proto.InternalMessageInfo

func (m *MsgMicrotx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgMicrotx) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgMicrotx) GetAmounts() []types.Coin {
	if m != nil {
		return m.Amounts
	}
	return nil
}

type MsgMicrotxResponse struct {
}

func (m *MsgMicrotxResponse) Reset()         { *m = MsgMicrotxResponse{} }
func (m *MsgMicrotxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMicrotxResponse) ProtoMessage()    {}
func (*MsgMicrotxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{1}
}
func (m *MsgMicrotxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMicrotxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMicrotxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMicrotxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMicrotxResponse.Merge(m, src)
}
func (m *MsgMicrotxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMicrotxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMicrotxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMicrotxResponse proto.InternalMessageInfo

// A type for the block's event log, every successful Microtx must create one of
// these in the event log
type EventMicrotx struct {
	Sender   string       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string       `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amounts  []types.Coin `protobuf:"bytes,3,rep,name=amounts,proto3" json:"amounts"`
	Fee      []types.Coin `protobuf:"bytes,4,rep,name=fee,proto3" json:"fee"`
}

func (m *EventMicrotx) Reset()         { *m = EventMicrotx{} }
func (m *EventMicrotx) String() string { return proto.CompactTextString(m) }
func (*EventMicrotx) ProtoMessage()    {}
func (*EventMicrotx) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{2}
}
func (m *EventMicrotx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMicrotx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMicrotx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMicrotx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMicrotx.Merge(m, src)
}
func (m *EventMicrotx) XXX_Size() int {
	return m.Size()
}
func (m *EventMicrotx) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMicrotx.DiscardUnknown(m)
}

var xxx_messageInfo_EventMicrotx proto.InternalMessageInfo

func (m *EventMicrotx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *EventMicrotx) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *EventMicrotx) GetAmounts() []types.Coin {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *EventMicrotx) GetFee() []types.Coin {
	if m != nil {
		return m.Fee
	}
	return nil
}

// A type for the block's event log recording when a TokenizedAccount has a received balance redirected to
// its registered TokenizedAccountNFT
type EventBalanceRedirect struct {
	Account string       `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amounts []types.Coin `protobuf:"bytes,2,rep,name=amounts,proto3" json:"amounts"`
}

func (m *EventBalanceRedirect) Reset()         { *m = EventBalanceRedirect{} }
func (m *EventBalanceRedirect) String() string { return proto.CompactTextString(m) }
func (*EventBalanceRedirect) ProtoMessage()    {}
func (*EventBalanceRedirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{3}
}
func (m *EventBalanceRedirect) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBalanceRedirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBalanceRedirect.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBalanceRedirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBalanceRedirect.Merge(m, src)
}
func (m *EventBalanceRedirect) XXX_Size() int {
	return m.Size()
}
func (m *EventBalanceRedirect) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBalanceRedirect.DiscardUnknown(m)
}

var xxx_messageInfo_EventBalanceRedirect proto.InternalMessageInfo

func (m *EventBalanceRedirect) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EventBalanceRedirect) GetAmounts() []types.Coin {
	if m != nil {
		return m.Amounts
	}
	return nil
}

// Records critical information about a Tokenized Account
// TOKENIZED_ACCOUNT The bech32 address of the tokenized account
// OWNER The bech32 address of the account now in control of the token
// NFT_ADDRESS The EVM address of the token contract in control of the tokenized account's excess profits
type TokenizedAccount struct {
	Owner            string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenizedAccount string `protobuf:"bytes,2,opt,name=tokenized_account,json=tokenizedAccount,proto3" json:"tokenized_account,omitempty"`
	NftAddress       string `protobuf:"bytes,3,opt,name=nft_address,json=nftAddress,proto3" json:"nft_address,omitempty"`
}

func (m *TokenizedAccount) Reset()         { *m = TokenizedAccount{} }
func (m *TokenizedAccount) String() string { return proto.CompactTextString(m) }
func (*TokenizedAccount) ProtoMessage()    {}
func (*TokenizedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{4}
}
func (m *TokenizedAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenizedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenizedAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenizedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenizedAccount.Merge(m, src)
}
func (m *TokenizedAccount) XXX_Size() int {
	return m.Size()
}
func (m *TokenizedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenizedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_TokenizedAccount proto.InternalMessageInfo

func (m *TokenizedAccount) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TokenizedAccount) GetTokenizedAccount() string {
	if m != nil {
		return m.TokenizedAccount
	}
	return ""
}

func (m *TokenizedAccount) GetNftAddress() string {
	if m != nil {
		return m.NftAddress
	}
	return ""
}

// MsgTokenizeAccount A Msg meant to convert a wallet into a piece of Liquid Infrastructure,
// by creating a NonFungibleToken within the Althea L1 EVM which will control all balances
// held by the Tokenized Account (beyond a configurable threshold). The tokenized account itself
// will be the initial owner of the NFT, and must transfer control through the EVM NFT contract
// SENDER The bech32 address of the account to tokenize, must also be the signer of the message
type MsgTokenizeAccount struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgTokenizeAccount) Reset()         { *m = MsgTokenizeAccount{} }
func (m *MsgTokenizeAccount) String() string { return proto.CompactTextString(m) }
func (*MsgTokenizeAccount) ProtoMessage()    {}
func (*MsgTokenizeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{5}
}
func (m *MsgTokenizeAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTokenizeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTokenizeAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTokenizeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTokenizeAccount.Merge(m, src)
}
func (m *MsgTokenizeAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgTokenizeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTokenizeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTokenizeAccount proto.InternalMessageInfo

func (m *MsgTokenizeAccount) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

// MsgTokenizeAccountResponse potentially returns useful information from the tokenization of an account
type MsgTokenizeAccountResponse struct {
	Account *TokenizedAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *MsgTokenizeAccountResponse) Reset()         { *m = MsgTokenizeAccountResponse{} }
func (m *MsgTokenizeAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTokenizeAccountResponse) ProtoMessage()    {}
func (*MsgTokenizeAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{6}
}
func (m *MsgTokenizeAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTokenizeAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTokenizeAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTokenizeAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTokenizeAccountResponse.Merge(m, src)
}
func (m *MsgTokenizeAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTokenizeAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTokenizeAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTokenizeAccountResponse proto.InternalMessageInfo

func (m *MsgTokenizeAccountResponse) GetAccount() *TokenizedAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

// A type for the block's event log, every successful TokenizeAccount must create one of
// these in the event log
type EventAccountTokenized struct {
	Owned      string `protobuf:"bytes,1,opt,name=owned,proto3" json:"owned,omitempty"`
	NftAddress string `protobuf:"bytes,2,opt,name=nft_address,json=nftAddress,proto3" json:"nft_address,omitempty"`
}

func (m *EventAccountTokenized) Reset()         { *m = EventAccountTokenized{} }
func (m *EventAccountTokenized) String() string { return proto.CompactTextString(m) }
func (*EventAccountTokenized) ProtoMessage()    {}
func (*EventAccountTokenized) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{7}
}
func (m *EventAccountTokenized) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAccountTokenized) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAccountTokenized.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAccountTokenized) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountTokenized.Merge(m, src)
}
func (m *EventAccountTokenized) XXX_Size() int {
	return m.Size()
}
func (m *EventAccountTokenized) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountTokenized.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountTokenized proto.InternalMessageInfo

func (m *EventAccountTokenized) GetOwned() string {
	if m != nil {
		return m.Owned
	}
	return ""
}

func (m *EventAccountTokenized) GetNftAddress() string {
	if m != nil {
		return m.NftAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgMicrotx)(nil), "microtx.v1.MsgMicrotx")
	proto.RegisterType((*MsgMicrotxResponse)(nil), "microtx.v1.MsgMicrotxResponse")
	proto.RegisterType((*EventMicrotx)(nil), "microtx.v1.EventMicrotx")
	proto.RegisterType((*EventBalanceRedirect)(nil), "microtx.v1.EventBalanceRedirect")
	proto.RegisterType((*TokenizedAccount)(nil), "microtx.v1.TokenizedAccount")
	proto.RegisterType((*MsgTokenizeAccount)(nil), "microtx.v1.MsgTokenizeAccount")
	proto.RegisterType((*MsgTokenizeAccountResponse)(nil), "microtx.v1.MsgTokenizeAccountResponse")
	proto.RegisterType((*EventAccountTokenized)(nil), "microtx.v1.EventAccountTokenized")
}

func init() { proto.RegisterFile("microtx/v1/msgs.proto", fileDescriptor_4ddee508b32d6f4e) }

var fileDescriptor_4ddee508b32d6f4e = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcd, 0x8a, 0x13, 0x41,
	0x10, 0xce, 0x24, 0xeb, 0x46, 0x2b, 0x82, 0xeb, 0x98, 0x48, 0x1c, 0xc3, 0xec, 0x32, 0x88, 0x2c,
	0xa8, 0xd3, 0x24, 0x82, 0xe0, 0x71, 0x23, 0xde, 0x8c, 0x87, 0xb0, 0x27, 0x0f, 0x2e, 0x9d, 0x9e,
	0xca, 0xa4, 0xd9, 0xa4, 0x3b, 0x4c, 0xf7, 0x8e, 0xab, 0x1e, 0x04, 0x9f, 0x40, 0xf0, 0x45, 0x7c,
	0x8c, 0x3d, 0x2e, 0x78, 0xf1, 0x24, 0x92, 0x88, 0xcf, 0x21, 0xf3, 0xd3, 0x93, 0x71, 0xfc, 0x41,
	0x4f, 0xde, 0xba, 0xaa, 0xbe, 0xfe, 0xea, 0xeb, 0xaf, 0x6a, 0x06, 0x3a, 0x0b, 0xce, 0x22, 0xa9,
	0x4f, 0x49, 0xdc, 0x27, 0x0b, 0x15, 0x2a, 0x7f, 0x19, 0x49, 0x2d, 0x6d, 0xc8, 0xd3, 0x7e, 0xdc,
	0x77, 0x5c, 0x26, 0xd5, 0x42, 0x2a, 0x32, 0xa1, 0x0a, 0x49, 0xdc, 0x9f, 0xa0, 0xa6, 0x7d, 0xc2,
	0x24, 0x17, 0x19, 0xd6, 0x69, 0x87, 0x32, 0x94, 0xe9, 0x91, 0x24, 0xa7, 0x3c, 0xdb, 0x0b, 0xa5,
	0x0c, 0xe7, 0x48, 0xe8, 0x92, 0x13, 0x2a, 0x84, 0xd4, 0x54, 0x73, 0x29, 0x72, 0x7e, 0xef, 0x35,
	0xc0, 0x48, 0x85, 0xa3, 0xac, 0x89, 0x7d, 0x1d, 0xb6, 0x15, 0x8a, 0x00, 0xa3, 0xae, 0xb5, 0x67,
	0xed, 0x5f, 0x1a, 0xe7, 0x91, 0xed, 0xc0, 0xc5, 0x08, 0x19, 0xf2, 0x18, 0xa3, 0x6e, 0x3d, 0xad,
	0x14, 0xb1, 0xfd, 0x10, 0x9a, 0x74, 0x21, 0x4f, 0x84, 0x56, 0xdd, 0xc6, 0x5e, 0x63, 0xbf, 0x35,
	0xb8, 0xe1, 0x67, 0x3a, 0xfd, 0x44, 0xa7, 0x9f, 0xeb, 0xf4, 0x1f, 0x49, 0x2e, 0x86, 0x5b, 0x67,
	0x9f, 0x77, 0x6b, 0x63, 0x83, 0xf7, 0xda, 0x60, 0x6f, 0x9a, 0x8f, 0x51, 0x2d, 0xa5, 0x50, 0xe8,
	0x7d, 0xb0, 0xe0, 0xf2, 0xe3, 0x18, 0x85, 0xfe, 0x3f, 0xaa, 0xec, 0x3e, 0x34, 0xa6, 0x88, 0xdd,
	0xad, 0xbf, 0xbb, 0x96, 0x60, 0xbd, 0x63, 0x68, 0xa7, 0x8a, 0x87, 0x74, 0x4e, 0x05, 0xc3, 0x31,
	0x06, 0x3c, 0x42, 0xa6, 0xed, 0x2e, 0x34, 0x29, 0x63, 0x09, 0x6d, 0x2e, 0xdd, 0x84, 0x65, 0x7d,
	0xf5, 0x7f, 0x74, 0x2d, 0x86, 0x9d, 0x43, 0x79, 0x8c, 0x82, 0xbf, 0xc2, 0xe0, 0x20, 0xa7, 0x6b,
	0xc3, 0x05, 0xf9, 0x42, 0x14, 0x0e, 0x65, 0x81, 0x7d, 0x07, 0xae, 0x6a, 0x83, 0x3c, 0x32, 0x42,
	0x32, 0xa7, 0x76, 0x74, 0x95, 0x62, 0x17, 0x5a, 0x62, 0xaa, 0x8f, 0x68, 0x10, 0x44, 0xa8, 0x12,
	0xd7, 0x12, 0x18, 0x88, 0xa9, 0x3e, 0xc8, 0x32, 0xde, 0xdd, 0x74, 0x5a, 0xa6, 0xb5, 0xb9, 0xf6,
	0x9b, 0xe1, 0x78, 0x87, 0xe0, 0xfc, 0x8c, 0x36, 0x33, 0xb6, 0x1f, 0xfc, 0x68, 0x4c, 0x6b, 0xd0,
	0xf3, 0x37, 0x8b, 0xee, 0x57, 0x9f, 0x57, 0xd8, 0xe6, 0x3d, 0x85, 0x4e, 0x6a, 0x74, 0x5e, 0x28,
	0x80, 0xc6, 0x80, 0xa0, 0x6c, 0x40, 0x50, 0x7d, 0x53, 0xbd, 0xfa, 0xa6, 0xc1, 0x37, 0x0b, 0x1a,
	0x23, 0x15, 0xda, 0xcf, 0xa1, 0x59, 0x6c, 0x5b, 0x59, 0xc9, 0x66, 0x3d, 0x1d, 0xf7, 0xd7, 0xf9,
	0x62, 0x6d, 0x6f, 0xbe, 0xfd, 0xf8, 0xf5, 0x7d, 0xbd, 0xe3, 0x5d, 0x23, 0xe5, 0x2f, 0x39, 0x27,
	0x7d, 0x03, 0x57, 0xaa, 0xc6, 0x55, 0xf9, 0x2a, 0x75, 0xe7, 0xf6, 0x9f, 0xeb, 0x45, 0xdf, 0x5b,
	0x69, 0x5f, 0xd7, 0xeb, 0x95, 0xfb, 0x9a, 0xe9, 0x9a, 0xa9, 0x0f, 0x9f, 0x9c, 0xad, 0x5c, 0xeb,
	0x7c, 0xe5, 0x5a, 0x5f, 0x56, 0xae, 0xf5, 0x6e, 0xed, 0xd6, 0xce, 0xd7, 0x6e, 0xed, 0xd3, 0xda,
	0xad, 0x3d, 0x1b, 0x84, 0x5c, 0xcf, 0x4e, 0x26, 0x3e, 0x93, 0x0b, 0x42, 0xe7, 0x7a, 0x86, 0xf4,
	0x9e, 0x40, 0x6d, 0x8e, 0x6c, 0x46, 0xb9, 0x20, 0xa7, 0x05, 0xb7, 0x7e, 0xb9, 0x44, 0x35, 0xd9,
	0x4e, 0x7f, 0x1e, 0xf7, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe3, 0x2c, 0x8f, 0xb5, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// The Microtx service handles payments to Althea accounts
	Microtx(ctx context.Context, in *MsgMicrotx, opts ...grpc.CallOption) (*MsgMicrotxResponse, error)
	// The TokenizeAccount service converts a wallet into a piece of Liquid Infrastructure
	TokenizeAccount(ctx context.Context, in *MsgTokenizeAccount, opts ...grpc.CallOption) (*MsgTokenizeAccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Microtx(ctx context.Context, in *MsgMicrotx, opts ...grpc.CallOption) (*MsgMicrotxResponse, error) {
	out := new(MsgMicrotxResponse)
	err := c.cc.Invoke(ctx, "/microtx.v1.Msg/Microtx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TokenizeAccount(ctx context.Context, in *MsgTokenizeAccount, opts ...grpc.CallOption) (*MsgTokenizeAccountResponse, error) {
	out := new(MsgTokenizeAccountResponse)
	err := c.cc.Invoke(ctx, "/microtx.v1.Msg/TokenizeAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// The Microtx service handles payments to Althea accounts
	Microtx(context.Context, *MsgMicrotx) (*MsgMicrotxResponse, error)
	// The TokenizeAccount service converts a wallet into a piece of Liquid Infrastructure
	TokenizeAccount(context.Context, *MsgTokenizeAccount) (*MsgTokenizeAccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Microtx(ctx context.Context, req *MsgMicrotx) (*MsgMicrotxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Microtx not implemented")
}
func (*UnimplementedMsgServer) TokenizeAccount(ctx context.Context, req *MsgTokenizeAccount) (*MsgTokenizeAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenizeAccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Microtx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMicrotx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Microtx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microtx.v1.Msg/Microtx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Microtx(ctx, req.(*MsgMicrotx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TokenizeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTokenizeAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TokenizeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microtx.v1.Msg/TokenizeAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TokenizeAccount(ctx, req.(*MsgTokenizeAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microtx.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Microtx",
			Handler:    _Msg_Microtx_Handler,
		},
		{
			MethodName: "TokenizeAccount",
			Handler:    _Msg_TokenizeAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microtx/v1/msgs.proto",
}

func (m *MsgMicrotx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMicrotx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMicrotx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMicrotxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMicrotxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMicrotxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *EventMicrotx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMicrotx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMicrotx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fee) > 0 {
		for iNdEx := len(m.Fee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBalanceRedirect) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBalanceRedirect) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBalanceRedirect) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenizedAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenizedAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenizedAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftAddress) > 0 {
		i -= len(m.NftAddress)
		copy(dAtA[i:], m.NftAddress)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.NftAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenizedAccount) > 0 {
		i -= len(m.TokenizedAccount)
		copy(dAtA[i:], m.TokenizedAccount)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.TokenizedAccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTokenizeAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTokenizeAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTokenizeAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTokenizeAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTokenizeAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTokenizeAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgs(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventAccountTokenized) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAccountTokenized) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAccountTokenized) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftAddress) > 0 {
		i -= len(m.NftAddress)
		copy(dAtA[i:], m.NftAddress)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.NftAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owned) > 0 {
		i -= len(m.Owned)
		copy(dAtA[i:], m.Owned)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Owned)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMicrotx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	return n
}

func (m *MsgMicrotxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *EventMicrotx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	if len(m.Fee) > 0 {
		for _, e := range m.Fee {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	return n
}

func (m *EventBalanceRedirect) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	return n
}

func (m *TokenizedAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.TokenizedAccount)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.NftAddress)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func (m *MsgTokenizeAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func (m *MsgTokenizeAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func (m *EventAccountTokenized) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owned)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.NftAddress)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func sovMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgs(x uint64) (n int) {
	return sovMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMicrotx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMicrotx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMicrotx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMicrotxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMicrotxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMicrotxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMicrotx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMicrotx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMicrotx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = append(m.Fee, types.Coin{})
			if err := m.Fee[len(m.Fee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBalanceRedirect) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBalanceRedirect: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBalanceRedirect: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenizedAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenizedAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenizedAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenizedAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenizedAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTokenizeAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTokenizeAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTokenizeAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTokenizeAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTokenizeAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTokenizeAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &TokenizedAccount{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAccountTokenized) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAccountTokenized: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAccountTokenized: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owned = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgs = fmt.Errorf("proto: unexpected end of group")
)
