// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: althea/microtx/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Query the current microtx params
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// Query the additional fee paid on MsgMicrotx, determined by governance
type QueryMicrotxFeeRequest struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryMicrotxFeeRequest) Reset()         { *m = QueryMicrotxFeeRequest{} }
func (m *QueryMicrotxFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMicrotxFeeRequest) ProtoMessage()    {}
func (*QueryMicrotxFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{2}
}
func (m *QueryMicrotxFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMicrotxFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMicrotxFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMicrotxFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMicrotxFeeRequest.Merge(m, src)
}
func (m *QueryMicrotxFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMicrotxFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMicrotxFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMicrotxFeeRequest proto.InternalMessageInfo

func (m *QueryMicrotxFeeRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type QueryMicrotxFeeResponse struct {
	FeeAmount uint64 `protobuf:"varint,1,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
}

func (m *QueryMicrotxFeeResponse) Reset()         { *m = QueryMicrotxFeeResponse{} }
func (m *QueryMicrotxFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMicrotxFeeResponse) ProtoMessage()    {}
func (*QueryMicrotxFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{3}
}
func (m *QueryMicrotxFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMicrotxFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMicrotxFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMicrotxFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMicrotxFeeResponse.Merge(m, src)
}
func (m *QueryMicrotxFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMicrotxFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMicrotxFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMicrotxFeeResponse proto.InternalMessageInfo

func (m *QueryMicrotxFeeResponse) GetFeeAmount() uint64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

// Query the Liquid Infrastructure accounts known to the module
type QueryLiquidAccountsRequest struct {
}

func (m *QueryLiquidAccountsRequest) Reset()         { *m = QueryLiquidAccountsRequest{} }
func (m *QueryLiquidAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidAccountsRequest) ProtoMessage()    {}
func (*QueryLiquidAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{4}
}
func (m *QueryLiquidAccountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidAccountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidAccountsRequest.Merge(m, src)
}
func (m *QueryLiquidAccountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidAccountsRequest proto.InternalMessageInfo

type QueryLiquidAccountsResponse struct {
	Accounts []*LiquidInfrastructureAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (m *QueryLiquidAccountsResponse) Reset()         { *m = QueryLiquidAccountsResponse{} }
func (m *QueryLiquidAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidAccountsResponse) ProtoMessage()    {}
func (*QueryLiquidAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{5}
}
func (m *QueryLiquidAccountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidAccountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidAccountsResponse.Merge(m, src)
}
func (m *QueryLiquidAccountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidAccountsResponse proto.InternalMessageInfo

func (m *QueryLiquidAccountsResponse) GetAccounts() []*LiquidInfrastructureAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Query for info about one particular Liquid Infrastructure account
// OWNER if a bech32 address is provided, potenitally many accounts will be returned
// ACCOUNT if a bech32 address is provided, the owner and nft contract address will be returned
// NFT if a EVM address is provided and happens to be a LiquidInfrastructureNFT contract, the owner and account will be returned
type QueryLiquidAccountRequest struct {
	Owner   string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nft     string `protobuf:"bytes,3,opt,name=nft,proto3" json:"nft,omitempty"`
}

func (m *QueryLiquidAccountRequest) Reset()         { *m = QueryLiquidAccountRequest{} }
func (m *QueryLiquidAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidAccountRequest) ProtoMessage()    {}
func (*QueryLiquidAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{6}
}
func (m *QueryLiquidAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidAccountRequest.Merge(m, src)
}
func (m *QueryLiquidAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidAccountRequest proto.InternalMessageInfo

func (m *QueryLiquidAccountRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryLiquidAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryLiquidAccountRequest) GetNft() string {
	if m != nil {
		return m.Nft
	}
	return ""
}

type QueryLiquidAccountResponse struct {
	Accounts []*LiquidInfrastructureAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (m *QueryLiquidAccountResponse) Reset()         { *m = QueryLiquidAccountResponse{} }
func (m *QueryLiquidAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidAccountResponse) ProtoMessage()    {}
func (*QueryLiquidAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd499ab5e6b38630, []int{7}
}
func (m *QueryLiquidAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidAccountResponse.Merge(m, src)
}
func (m *QueryLiquidAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidAccountResponse proto.InternalMessageInfo

func (m *QueryLiquidAccountResponse) GetAccounts() []*LiquidInfrastructureAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "althea.microtx.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "althea.microtx.v1.QueryParamsResponse")
	proto.RegisterType((*QueryMicrotxFeeRequest)(nil), "althea.microtx.v1.QueryMicrotxFeeRequest")
	proto.RegisterType((*QueryMicrotxFeeResponse)(nil), "althea.microtx.v1.QueryMicrotxFeeResponse")
	proto.RegisterType((*QueryLiquidAccountsRequest)(nil), "althea.microtx.v1.QueryLiquidAccountsRequest")
	proto.RegisterType((*QueryLiquidAccountsResponse)(nil), "althea.microtx.v1.QueryLiquidAccountsResponse")
	proto.RegisterType((*QueryLiquidAccountRequest)(nil), "althea.microtx.v1.QueryLiquidAccountRequest")
	proto.RegisterType((*QueryLiquidAccountResponse)(nil), "althea.microtx.v1.QueryLiquidAccountResponse")
}

func init() { proto.RegisterFile("althea/microtx/v1/query.proto", fileDescriptor_bd499ab5e6b38630) }

var fileDescriptor_bd499ab5e6b38630 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x6f, 0x12, 0x41,
	0x14, 0x66, 0x0b, 0x45, 0xfb, 0x1a, 0x8d, 0x8e, 0xa4, 0x85, 0x2d, 0x2c, 0xcd, 0x1a, 0x4d, 0x35,
	0xb2, 0x2b, 0x78, 0xd0, 0x6b, 0x7b, 0x30, 0xa9, 0xa9, 0x46, 0x39, 0x9a, 0x18, 0x32, 0xc5, 0xc7,
	0xb2, 0x09, 0xcc, 0xc0, 0xce, 0x6c, 0x6d, 0xaf, 0xc6, 0x1f, 0xd0, 0x44, 0xff, 0x86, 0xff, 0xa3,
	0xc7, 0x26, 0x5e, 0x3c, 0x19, 0x03, 0xfe, 0x10, 0xc3, 0xcc, 0x2c, 0x96, 0xec, 0x12, 0xb9, 0xf4,
	0xf6, 0xe6, 0xbd, 0xef, 0xfb, 0xde, 0xf7, 0xb2, 0x1f, 0x40, 0x8d, 0x0e, 0x64, 0x1f, 0xa9, 0x3f,
	0x0c, 0xbb, 0x11, 0x97, 0xa7, 0xfe, 0x49, 0xd3, 0x1f, 0xc7, 0x18, 0x9d, 0x79, 0xa3, 0x88, 0x4b,
	0x4e, 0xee, 0xea, 0xb1, 0x67, 0xc6, 0xde, 0x49, 0xd3, 0xae, 0xa7, 0x19, 0x01, 0x32, 0x14, 0xa1,
	0xd0, 0x1c, 0xbb, 0x9a, 0x06, 0x0c, 0x45, 0x90, 0x4c, 0x4b, 0x01, 0x0f, 0xb8, 0x2a, 0xfd, 0x59,
	0x95, 0x70, 0x02, 0xce, 0x83, 0x01, 0xfa, 0x74, 0x14, 0xfa, 0x94, 0x31, 0x2e, 0xa9, 0x0c, 0x39,
	0x33, 0x1c, 0xb7, 0x04, 0xe4, 0xdd, 0xcc, 0xd4, 0x5b, 0x1a, 0xd1, 0xa1, 0x68, 0xe3, 0x38, 0x46,
	0x21, 0xdd, 0x37, 0x70, 0x6f, 0xa1, 0x2b, 0x46, 0x9c, 0x09, 0x24, 0xcf, 0xa1, 0x38, 0x52, 0x9d,
	0xb2, 0xb5, 0x6b, 0xed, 0x6d, 0xb6, 0x2a, 0x5e, 0xea, 0x06, 0x4f, 0x53, 0x0e, 0x0a, 0x17, 0xbf,
	0xea, 0xb9, 0xb6, 0x81, 0xbb, 0x4f, 0x61, 0x4b, 0xe9, 0xbd, 0xd6, 0xb8, 0x97, 0x88, 0x66, 0x13,
	0xd9, 0x82, 0x22, 0x1d, 0xf2, 0x98, 0x49, 0x25, 0x59, 0x68, 0x9b, 0x97, 0xfb, 0x02, 0xb6, 0x53,
	0x0c, 0xe3, 0xa2, 0x06, 0xd0, 0x43, 0xec, 0x2c, 0xd0, 0x36, 0x7a, 0x88, 0xfb, 0x9a, 0x59, 0x05,
	0x5b, 0x31, 0x8f, 0xc2, 0x71, 0x1c, 0x7e, 0xdc, 0xef, 0x76, 0x67, 0xdd, 0xf9, 0x65, 0x21, 0xec,
	0x64, 0x4e, 0x8d, 0xf6, 0x2b, 0xb8, 0x49, 0x4d, 0xaf, 0x6c, 0xed, 0xe6, 0xf7, 0x36, 0x5b, 0x5e,
	0xc6, 0x8d, 0x9a, 0x7c, 0xc8, 0x7a, 0x11, 0x15, 0x32, 0x8a, 0xbb, 0x32, 0x8e, 0xd0, 0x48, 0xb5,
	0xe7, 0x7c, 0xf7, 0x03, 0x54, 0xd2, 0xab, 0x92, 0xbb, 0x4b, 0xb0, 0xce, 0x3f, 0x31, 0x8c, 0x94,
	0xff, 0x8d, 0xb6, 0x7e, 0x90, 0x32, 0xdc, 0x30, 0xf4, 0xf2, 0x9a, 0xea, 0x27, 0x4f, 0x72, 0x07,
	0xf2, 0xac, 0x27, 0xcb, 0x79, 0xd5, 0x9d, 0x95, 0x6e, 0x3f, 0xeb, 0xce, 0xeb, 0x38, 0xa4, 0xf5,
	0xbd, 0x00, 0xeb, 0x6a, 0x15, 0x11, 0x50, 0xd4, 0xdf, 0x97, 0x3c, 0xc8, 0x50, 0x4b, 0x07, 0xc9,
	0x7e, 0xf8, 0x3f, 0x98, 0xb6, 0xeb, 0xda, 0x9f, 0x7f, 0xfc, 0xf9, 0xba, 0x56, 0x22, 0xe4, 0x6a,
	0xb4, 0x75, 0x78, 0xc8, 0x17, 0x0b, 0xe0, 0x5f, 0x0c, 0xc8, 0xa3, 0x65, 0x92, 0xa9, 0x70, 0xd9,
	0x8f, 0x57, 0x81, 0x1a, 0x07, 0x75, 0xe5, 0xa0, 0x42, 0xb6, 0x17, 0x7e, 0x5c, 0xba, 0xec, 0xf4,
	0x10, 0xc9, 0x37, 0x0b, 0x6e, 0x2f, 0xa6, 0x86, 0x34, 0x96, 0xe9, 0x67, 0x66, 0xcf, 0xf6, 0x56,
	0x85, 0x1b, 0x4b, 0xf7, 0x95, 0xa5, 0x1a, 0xd9, 0xb9, 0x6a, 0x69, 0xa0, 0xb0, 0x9d, 0xe4, 0xe3,
	0x90, 0x73, 0x0b, 0x6e, 0x2d, 0xf0, 0xc9, 0x93, 0x95, 0xd6, 0x24, 0xa6, 0x1a, 0x2b, 0xa2, 0x8d,
	0x27, 0x57, 0x79, 0xaa, 0x12, 0x7b, 0xb9, 0xa7, 0x83, 0xc3, 0x8b, 0x89, 0x63, 0x5d, 0x4e, 0x1c,
	0xeb, 0xf7, 0xc4, 0xb1, 0xce, 0xa7, 0x4e, 0xee, 0x72, 0xea, 0xe4, 0x7e, 0x4e, 0x9d, 0xdc, 0x7b,
	0x3f, 0x08, 0x65, 0x3f, 0x3e, 0xf6, 0xba, 0x7c, 0xe8, 0xeb, 0xb5, 0x0d, 0x86, 0x32, 0x29, 0x8f,
	0x9a, 0xfe, 0xe9, 0x5c, 0x56, 0x9e, 0x8d, 0x50, 0x1c, 0x17, 0xd5, 0xbf, 0xd4, 0xb3, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xdb, 0xd1, 0xd4, 0x32, 0x4c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Query the current microtx params
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Get an authoritative fee amount which must be paid on Microtx
	MicrotxFee(ctx context.Context, in *QueryMicrotxFeeRequest, opts ...grpc.CallOption) (*QueryMicrotxFeeResponse, error)
	// Get all of the Liquid Infrastructure accounts known to the module
	LiquidAccounts(ctx context.Context, in *QueryLiquidAccountsRequest, opts ...grpc.CallOption) (*QueryLiquidAccountsResponse, error)
	// Get info about one particular Liquid Infrastructure account by owner, bech32 address, or nft address
	// Make HTTP GET requests like:
	// * `GET /microtx/v1/liquid_account?owner=althea1...`
	// * `GET /microtx/v1/liquid_account?owner=0xABCDE...`
	// * `GET /microtx/v1/liquid_account?account=althea1...`
	// * `GET /microtx/v1/liquid_account?nft=0xABCDE...`
	LiquidAccount(ctx context.Context, in *QueryLiquidAccountRequest, opts ...grpc.CallOption) (*QueryLiquidAccountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/althea.microtx.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MicrotxFee(ctx context.Context, in *QueryMicrotxFeeRequest, opts ...grpc.CallOption) (*QueryMicrotxFeeResponse, error) {
	out := new(QueryMicrotxFeeResponse)
	err := c.cc.Invoke(ctx, "/althea.microtx.v1.Query/MicrotxFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LiquidAccounts(ctx context.Context, in *QueryLiquidAccountsRequest, opts ...grpc.CallOption) (*QueryLiquidAccountsResponse, error) {
	out := new(QueryLiquidAccountsResponse)
	err := c.cc.Invoke(ctx, "/althea.microtx.v1.Query/LiquidAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LiquidAccount(ctx context.Context, in *QueryLiquidAccountRequest, opts ...grpc.CallOption) (*QueryLiquidAccountResponse, error) {
	out := new(QueryLiquidAccountResponse)
	err := c.cc.Invoke(ctx, "/althea.microtx.v1.Query/LiquidAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Query the current microtx params
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Get an authoritative fee amount which must be paid on Microtx
	MicrotxFee(context.Context, *QueryMicrotxFeeRequest) (*QueryMicrotxFeeResponse, error)
	// Get all of the Liquid Infrastructure accounts known to the module
	LiquidAccounts(context.Context, *QueryLiquidAccountsRequest) (*QueryLiquidAccountsResponse, error)
	// Get info about one particular Liquid Infrastructure account by owner, bech32 address, or nft address
	// Make HTTP GET requests like:
	// * `GET /microtx/v1/liquid_account?owner=althea1...`
	// * `GET /microtx/v1/liquid_account?owner=0xABCDE...`
	// * `GET /microtx/v1/liquid_account?account=althea1...`
	// * `GET /microtx/v1/liquid_account?nft=0xABCDE...`
	LiquidAccount(context.Context, *QueryLiquidAccountRequest) (*QueryLiquidAccountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MicrotxFee(ctx context.Context, req *QueryMicrotxFeeRequest) (*QueryMicrotxFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MicrotxFee not implemented")
}
func (*UnimplementedQueryServer) LiquidAccounts(ctx context.Context, req *QueryLiquidAccountsRequest) (*QueryLiquidAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidAccounts not implemented")
}
func (*UnimplementedQueryServer) LiquidAccount(ctx context.Context, req *QueryLiquidAccountRequest) (*QueryLiquidAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidAccount not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/althea.microtx.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MicrotxFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMicrotxFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MicrotxFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/althea.microtx.v1.Query/MicrotxFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MicrotxFee(ctx, req.(*QueryMicrotxFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LiquidAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLiquidAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LiquidAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/althea.microtx.v1.Query/LiquidAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LiquidAccounts(ctx, req.(*QueryLiquidAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LiquidAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLiquidAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LiquidAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/althea.microtx.v1.Query/LiquidAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LiquidAccount(ctx, req.(*QueryLiquidAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "althea.microtx.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MicrotxFee",
			Handler:    _Query_MicrotxFee_Handler,
		},
		{
			MethodName: "LiquidAccounts",
			Handler:    _Query_LiquidAccounts_Handler,
		},
		{
			MethodName: "LiquidAccount",
			Handler:    _Query_LiquidAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "althea/microtx/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMicrotxFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMicrotxFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMicrotxFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryMicrotxFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMicrotxFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMicrotxFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FeeAmount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.FeeAmount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidAccountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidAccountsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidAccountsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLiquidAccountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidAccountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidAccountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for iNdEx := len(m.Accounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Accounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nft) > 0 {
		i -= len(m.Nft)
		copy(dAtA[i:], m.Nft)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nft)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for iNdEx := len(m.Accounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Accounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMicrotxFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	return n
}

func (m *QueryMicrotxFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FeeAmount != 0 {
		n += 1 + sovQuery(uint64(m.FeeAmount))
	}
	return n
}

func (m *QueryLiquidAccountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLiquidAccountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryLiquidAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Nft)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLiquidAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMicrotxFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMicrotxFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMicrotxFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMicrotxFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMicrotxFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMicrotxFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAmount", wireType)
			}
			m.FeeAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidAccountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidAccountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidAccountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidAccountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidAccountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidAccountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, &LiquidInfrastructureAccount{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nft", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nft = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, &LiquidInfrastructureAccount{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
